# -*- coding: utf-8 -*-
"""Performing Analysis of Meteorological Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpx2teDRvkNX3ViV7q1LhpmRy-unVQ-0
"""

import pandas as pd
from google.colab import files

upload = files.upload()

dataset = pd.read_csv('weatherHistory (1).csv')

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

dataset.head()

dataset.isnull().sum()

dataset.info()

dataset['Formatted Date']= pd.to_datetime(dataset['Formatted Date'], utc= True)

dataset['Formatted Date']

dataset = dataset.set_index('Formatted Date')
dataset.head()

data_columns = ['Apparent Temperature (C)', 'Humidity']
df_monthly_mean = dataset[data_columns].resample('MS').mean()
df_monthly_mean.head()

df_monthly_mean

df1= df_monthly_mean[df_monthly_mean.index.month==4]
print(df1)
print(df1.dtypes)

import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
plt.figure(figsize=(14,6))
plt.title("Variation in Apparent Temperature and Humidity with time")
sns.lineplot(data=df_monthly_mean)

df1 = df_monthly_mean[df_monthly_mean.index.month==4]
print(df1)
df1.dtypes

import matplotlib.dates as mdates
fig, ax = plt.subplots(figsize=(18,7))
ax.plot(df1.loc['2006-04-01':'2016-04-01', 'Apparent Temperature (C)'], marker='o', linestyle='-',label='Apparent Temperature (C)')
ax.plot(df1.loc['2006-04-01':'2016-04-01', 'Humidity'], marker='o', linestyle='-',label='Humidity')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%d %m %Y'))
ax.legend(loc ='center right')
ax.set_xlabel('Month of April')

sns.lmplot(x='Apparent Temperature (C)',y='Humidity',data=df_monthly_mean)
plt.show()